# Generated by Django 3.1.8 on 2023-08-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
