# Generated by Django 3.1.8 on 2023-08-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='catagory',
            field=models.CharField(choices=[('s', 'shirt'), ('sport', 'sports wear'), ('ow', 'out wear')], default='s', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lable',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondry'), ('d', 'danger')], default='p', max_length=5),
            preserve_default=False,
        ),
    ]
