# Generated by Django 3.1.8 on 2023-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230803_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quntity',
            field=models.IntegerField(default=1),
        ),
    ]
