# Generated by Django 3.1.8 on 2023-08-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_item_quntity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quntity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quntity',
            field=models.IntegerField(default=1),
        ),
    ]
